// Package plantdata bundles the static plant library into the binary so the
// server has no runtime dependency on the JSON files being present on disk.
package plantdata

import _ "embed"

// PlantsJSON is the curated library: ~86 plants with full care data.
//
//go:embed plants.json
var PlantsJSON []byte

// CatalogJSON is the broad European catalog imported from GBIF (latin names plus
// PL/EN vernaculars where available, no care schedules). Generated by
// cmd/plantimport. The blank default keeps builds working before a first import;
// the real file is committed and overrides it.
//
//go:embed catalog.json
var CatalogJSON []byte
