// Package plantdata bundles the static plant library into the binary so the
// server has no runtime dependency on the JSON files being present on disk.
package plantdata

import _ "embed"

// PlantsJSON is the curated library: ~86 plants with full care data.
//
//go:embed plants.json
var PlantsJSON []byte

// PlantsExtraJSON is the curated horticultural supplement: garden cultivars and
// varieties (cherry laurel cultivars, basil types, popular vegetable/herb
// cultivars, etc.) with care data. These are taxa GBIF omits or synonymizes.
//
//go:embed plants_extra.json
var PlantsExtraJSON []byte

// PlantsExtra2JSON is a second curated supplement that deepens under-covered
// categories — orchard fruit-tree cultivars (cherry, plum, pear, peach,
// apricot, walnut), more berries, and broader ornamentals/herbs/vegetables.
//
//go:embed plants_extra2.json
var PlantsExtra2JSON []byte

// CatalogJSON is the broad European catalog imported from GBIF (latin names plus
// PL/EN vernaculars where available, no care schedules). Generated by
// cmd/plantimport. The blank default keeps builds working before a first import;
// the real file is committed and overrides it.
//
//go:embed catalog.json
var CatalogJSON []byte

// EnrichmentJSON is a map of plant id → rich bilingual care data (description,
// fertilizing, diseases, tips, ...). Generated by the enrichment workflow.
//
//go:embed enrichment.json
var EnrichmentJSON []byte

// ImagesJSON is a map of plant id → open-source image (URL + license +
// attribution), fetched from Wikimedia Commons by cmd/imageimport.
//
//go:embed images.json
var ImagesJSON []byte
